### ISSUE TITLE
Running checklist to ask volunteer testers from D4BL National

### ISSUE THREAD

**Issue by emhsieh** [D4BL-DMV/dbl-legal-directory#8]
Hello, world!

I'm figuring this out. Please feel free to delete or resolve. Not sure if this belongs in Issues.

Access checklist, for testing/testers:

**Language Access** (#1)
- [ ] Spanish access (if no translation available yet, provide info on interpretation resources)
- [ ] Request language assistance button in DC's most used languages?

**Reading Level Access** (#9)
- [ ] Reading Level below grade 8, preferably grade 5 (hemingwayapp.com)
- [ ] What else am I not thinking of? A resource for assistance with the directory?
- [ ] All Sans serif fonts

**Web Content Access** (#2)
- [ ] All images have Image Description (better than alt-text)
- [ ] All videos have captions or transcript
- [ ] Able to generate or download text file to use with personal accessibility software like NVDA, or have offline
- [ ] Able to navigate with keyboard only (ARIA)
- [ ] Able to find X information using English screenreader (e.g. NVDA, Speechify)
- [ ] Desktop / tablet / mobile / different OS's
- [ ] Do things work with reeeealllllyyyy slow internet?
- [ ] All text sans serif? (better for dyslexia)

**Resources & Sources on Access, Accessibility, Disability**
- Will list things here that Dylan shared and more things I/we found or find

Will keep working on this. It is incomplete. Please add or suggest changes!

**Comment by dmadisetti** [comment]
Thanks @emhsieh
I linked the associated issues. I'm going to pin this one so that we can easily refer back to what needs to be done
